server:
  port: 8001

spring:
  application:
    name: CLOUD-PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root
    username: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhs.entity
eureka:
  instance:
    hostname: localhost
    instance-id: payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署