server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-feign

eureka:
  instance:
    hostname: localhost
    instance-id: payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka

#设置feign客户端超市时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    # feign日志级别
    com.zhs.cloudconsumerfeignorder80.service.PaymentFeignService: debug