server:
  port: 8004




spring:
  application:
    name: cloud-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root
    username: root

  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhs.entity